
FROM java:8
VOLUME /temp
ADD /server-1.0-SNAPSHOT.jar app.jar
#RUN bash -c 'touch/app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
EXPOSE 8080
#ENTRYPOINT ["java","-jar","/app.jar"]
